import matplotlib.pyplot as plt
def plot(h_t_loss,h_t_acc,h_v_loss,h_v_acc):
    plt.subplot(1,2,1)
    plt.plot(h_t_loss, label='Training Loss', color='blue', linewidth=2)
    plt.plot(h_v_loss, label='Validation Loss', color='red', linestyle='dashed', linewidth=2)
    plt.title("Loss Curve (Lower is Better)")
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.legend()
    plt.grid(True)
    plt.subplot(1,2,2)
    plt.plot(h_t_acc, label='Training Accuracy', color='blue', linewidth=2)
    plt.plot(h_v_acc, label='Validation Accuracy', color='red', linestyle='dashed', linewidth=2)
    plt.title("Accuracy Curve (Higher is Better)")
    plt.xlabel("Epochs")
    plt.ylabel("Accuracy (%)")
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()
#completed